security:
  algorithm:
    HS256
  access_token_expire_minutes:
    15
  refresh_token_expire_days:
    7
  web_admins:
    # pete@letkeman.ca = 111122296393493391055
    - 111122296393493391055
    - sub2

sql:
  active:
    sqlite
    # postgresql

  providers:
    sqlite:
      # sqlite specific config
      sqlite_file:
        swimlane.db

    postgresql:
      # postgresql specific config values, not credentails
