sequenceDiagram
    Member->>Admin: email admin with date/location, can't make and request a makeup time/location

    loop check capacity until a suitable slot is found
        Admin-->>Record: admin checks capacity at date & time
        alt has capacity
            Admin-->>Member: email the user to confirm
            Member-->>Admin: confirm
            Admin-->>Record: book the session
        else no capacity at the venue & time
            Admin-->>Member: email with alternative dates and time
        end
    end
