erDiagram
    frequency ||--o{ event : "frequency_id → frequency_id"
    event ||--|{ user : "event_id → event_id"
    event ||--o{ schedule : "event_id → schedule_id"
    user ||--o{ schedule : "members_id → member_id"
    venue ||--o{ schedule : "venue_id → venue_id"
    facility ||--o{ schedule : "facility_id → facility_id"


    frequency {
        automatic frequency_id
        string name
        string day_interval
        bool is_active
    }
    event {
        automatic event_id
        datetime start_date_time
        datetime end_date_time
        bool is_active
        string frequency_id
    }
    user {
        automatic user_id
        string sub
        string role
        string first_name_nonce
        string first_name_ciphertext
        string last_name_nonce
        string last_name_ciphertext
        string email_nonce
        string email_ciphertext
        datetime created_at
        datetime updated_at
        datetime delete_at
        bool is_deleted
        bool is_active
    }
    venue {
        automatic venue_id
        string facility_id
        string street
        string city
        string state
        string postal_code
        float cost
        bool is_active
    }
    facility {
        automatic facility_id
        string name
        string description
        int max_capicity
        int min_capicity
        bool is_active
    }
    schedule {
        automatic schedule_id
        string venue_id
        string member_id
        string event_id
        bool is_active
    }
